### ISSUE TITLE
Error - This line does not contain a recognised action

### ISSUE THREAD

**Issue by dinesh3434** [adegard/tagui_scripts#3]
When I try to use Tagui-Writer1.02.ahk and Tagui-Writer1.01.ahk, I get the following popup error as shown in the below screenshot. 
![image](https://user-images.githubusercontent.com/8008967/42412440-0887cc62-822a-11e8-988c-9966f7f7a13f.png)

I am using the following version of the AutoHotkey. 

![image](https://user-images.githubusercontent.com/8008967/42412452-299562a2-822a-11e8-9026-3f4dae742570.png)

**Comment by adegard** [comment]
Hi @dinesh3434 thank for your comment.
But are you sure you take code from here: https://github.com/adegard/tagui_scripts/blob/master/Tagui-Writer1.01.ahk
The text-line mentioned in popup error doesn't corrispond to any current line of code.

Also could you try the .exe version of Tagui Writer

For info, I use AutoHotKey newer version: 
![image](https://user-images.githubusercontent.com/23522577/42412966-2f602cb6-8217-11e8-9afb-b1559d4109bb.png)
Could you update it and check again.
Thanks!

**Comment by dinesh3434** [comment]
Thanks for the quick response. I used the file from the link that you have provided and  I checked again with the latest version as well. I get the following error and in the file I find the statement as well. I cannot use the .exe file due to security/firewall reasons. Can you please check and let me know if you need more information regarding the same. 

![image](https://user-images.githubusercontent.com/8008967/42417799-a01e2aa4-82b0-11e8-85b6-177b8543aeb8.png)

![image](https://user-images.githubusercontent.com/8008967/42417800-a68745a6-82b0-11e8-8cb8-e4d14b2c6847.png)

**Comment by adegard** [comment]
HI  @dinesh3434 
Unfortunatly our code rows aren't ahk code... 
Maybe you download the github page (HTML) instead of writing ahk code...

Try this procedure :
1. Go to https://github.com/adegard/tagui_scripts/blob/master/Tagui-Writer1.01.ahk . **Select and copy ONLY the code** to clipboard, like this, (using Ctrl+C):
![image](https://user-images.githubusercontent.com/23522577/42418352-c0b04d54-829e-11e8-869c-1b060da78e5e.png)
2. Open Notepad editor and paste your code. Save as "TaguiWriter.ahk"
3. To launch it: you just need to double click on file icon in windows explorer (without passing throught comand line)

Let me know if you solve issue.
thanks

**Comment by dinesh3434** [comment]
@adegard - Thanks for your quick response once again. The issue is resolved now. The issue was with the file being downloaded as AHK but containing HTML code :)
